name: pushing
favicon: null
layout_spectrum: 0.2694055924657732
typography_spectrum: 0.24124732241034508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6575592993758619
  lightness: 0.6387214281130582
  saturation: 0.26015863264910877
  rhythmicContrast: 0.627841534325853
purpose: []
